### ISSUE TITLE
Test Ticket

### ISSUE THREAD

**Issue by valentinajemuovic** [alptium/sasa.joksovic#1]
Hi @SasaOrca,

1. Write a comment below that you have received this test ticket.
2. Please tag me using @ then typing my GitHub name.
3. Close this ticket.
4. Go to https://github.com/orgs/alptium/teams/java-team/discussions and start doing the practical projects there (see discussions from bottom to top).

Thanks,
Valentina

**Comment by SasaOrca** [comment]
I am received test ticket
 @valentinacupac

2018-02-22 11:27 GMT+01:00 Valentina Cupać <notifications@github.com>:

**Comment by valentinajemuovic** [comment]
Thanks @SasaOrca, you can now click on the Close button to close the ticket.

**Comment by valentinajemuovic** [comment]
@SasaOrca, task done, I am now closing this ticket.
