### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by SasaOrca** [alptium/sasa.joksovic#2]

**Comment by SasaOrca** [comment]
task done @valentinacupac

**Comment by valentinajemuovic** [comment]
@SasaOrca, did you try to run this program in Eclipse? When I open Eclipse , I do not see the Main.java class... Let me know if you found it, or if any help is needed., then we can have a Skype meeting...

**Comment by SasaOrca** [comment]
Yes, I tried, but when I have finished task I have switched workspace, since GitHub and Eclipse wasn't connected, and because of that you can not see it. Should I do it again?

**Comment by valentinajemuovic** [comment]
@SasaOrca, not sure what happened, but now I re-tried opening it and it works.

Good work, closing this ticket.

**Comment by SasaOrca** [comment]
Ok, thanks!
